"""Initial migration

Revision ID: 352df74e2849
Revises: 
Create Date: 2025-12-12 17:29:29.869452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352df74e2849'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashedPassword', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phoneNumber')
    )
    op.create_table('farms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farmerId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sizeAcres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['farmerId'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farmId', sa.Integer(), nullable=False),
    sa.Column('cropName', sa.String(length=120), nullable=False),
    sa.Column('seasonName', sa.String(length=120), nullable=False),
    sa.Column('totalEstimatedCostUgx', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('totalActualCostUgx', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overDueActivitiesCount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmId'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seasonPlanId', sa.Integer(), nullable=False),
    sa.Column('activityType', sa.String(length=50), nullable=False),
    sa.Column('targetDate', sa.Date(), nullable=False),
    sa.Column('estimatedCostUgx', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'UPCOMING', 'OVERDUE', name='statustype'), nullable=False),
    sa.ForeignKeyConstraint(['seasonPlanId'], ['season_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actual_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seasonPlanId', sa.Integer(), nullable=False),
    sa.Column('activityType', sa.String(length=50), nullable=False),
    sa.Column('actualDate', sa.Date(), nullable=False),
    sa.Column('actualCostUgx', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('plannedActivityId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plannedActivityId'], ['planned_activities.id'], ),
    sa.ForeignKeyConstraint(['seasonPlanId'], ['season_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actual_activities')
    op.drop_table('planned_activities')
    op.drop_table('season_plans')
    op.drop_table('farms')
    op.drop_table('farmers')
    # ### end Alembic commands ###
