"""added gender on the farmer model

Revision ID: 5ebf4b1b5689
Revises: 8bc1cf34a916
Create Date: 2025-12-15 16:51:04.760234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebf4b1b5689'
down_revision: Union[str, Sequence[str], None] = '8bc1cf34a916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('gender', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'gender')
    # ### end Alembic commands ###
