"""Initial migration

Revision ID: 8bc1cf34a916
Revises: 352df74e2849
Create Date: 2025-12-12 22:12:25.083331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc1cf34a916'
down_revision: Union[str, Sequence[str], None] = '352df74e2849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season_plans', 'overDueActivitiesCount')
    op.drop_column('season_plans', 'totalActualCostUgx')
    op.drop_column('season_plans', 'totalEstimatedCostUgx')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_plans', sa.Column('totalEstimatedCostUgx', sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column('season_plans', sa.Column('totalActualCostUgx', sa.NUMERIC(precision=12, scale=2), nullable=False))
    op.add_column('season_plans', sa.Column('overDueActivitiesCount', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
